services:
  proxy:
    restart: "unless-stopped"
    build: ../proxy/
    image: photov/proxy
    environment:
      DOMAIN: ${DOMAIN}
    # https://caddyserver.com/docs/running#docker-compose
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config

  frontend:
    restart: "unless-stopped"
    build:
      context: ../frontend
      dockerfile: "../frontend/deploy/Dockerfile"
      network: host
    image: photov/frontend

  api:
    restart: "unless-stopped"
    build:
      context: ../backend
      network: host
    volumes:
      - ./creds:/creds
    image: photov/backend
    environment:
      PHOTOV_DOMAIN: ${DOMAIN}
      CREDS_FOLDER: "/creds"
      AUTH_SERVER_SECRET: "${AUTH_SERVER_SECRET}"
      # Make sure to keep that in sync with db service
      POSTGRES_PASSWORD: "${DB_PWD}"
      POSTGRES_USER: photov
      POSTGRES_DB: photov
      DB_HOST: db # the other database service hostname

  # See docs on https://hub.docker.com/_/postgres
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "${DB_PWD}"
      POSTGRES_USER: photov
      POSTGRES_DB: photov
    volumes:
      - ./data/pgdata:/var/lib/postgresql/18/docker
    # Only enable this in development !
    # ports:
    #   - "5432:5432"
