"""Add smartplug tables

Revision ID: 0fa698b0667e
Revises: 65483de9daac
Create Date: 2026-04-12 18:24:43.644329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "0fa698b0667e"
down_revision: Union[str, Sequence[str], None] = "65483de9daac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smartplug",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "smartplugmeasure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("smartplug_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["smartplug_id"],
            ["smartplug.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        op.f("userinstallationlink_user_id_fkey"),
        "userinstallationlink",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("userinstallationlink_installation_id_fkey"),
        "userinstallationlink",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("userinstallationlink_installation_id_fkey"),
        "userinstallationlink",
        "installation",
        ["installation_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("userinstallationlink_user_id_fkey"),
        "userinstallationlink",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_table("smartplugmeasure")
    op.drop_table("smartplug")
    # ### end Alembic commands ###
