"""Initial revision

Revision ID: 306c166bf56e
Revises:
Create Date: 2026-03-23 00:46:54.853662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "306c166bf56e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_installation_name"), "installation", ["name"], unique=False
    )
    op.create_table(
        "measure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("POWER", name="measuretype"), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("installation_id", sa.Integer(), nullable=True),
        sa.Column("solar_consumption", sa.Float(), nullable=False),
        sa.Column("solar_production", sa.Float(), nullable=False),
        sa.Column("grid_consumption", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["installation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "time", "installation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("measure")
    op.drop_index(op.f("ix_installation_name"), table_name="installation")
    op.drop_table("installation")
    # ### end Alembic commands ###
