"""Add user installation link

Revision ID: 65483de9daac
Revises: 8d5cf3f9c223
Create Date: 2026-03-26 22:56:24.558121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "65483de9daac"
down_revision: Union[str, Sequence[str], None] = "8d5cf3f9c223"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userinstallationlink",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "installation_id"),
        # NOTE: these 2 lines were added manually as a workaround...
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["installation_id"], ["installation.id"]),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userinstallationlink")
    # ### end Alembic commands ###
