"""Add installation id to smartplug

Revision ID: f09934c53fbc
Revises: 0fa698b0667e
Create Date: 2026-04-12 18:44:44.998018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "f09934c53fbc"
down_revision: Union[str, Sequence[str], None] = "0fa698b0667e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "smartplug", sa.Column("installation_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "smartplug", "installation", ["installation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "smartplug", type_="foreignkey")
    op.drop_column("smartplug", "installation_id")
    # ### end Alembic commands ###
