"""migration ml setup

Revision ID: f80ffeed5b87
Revises: ff93234e580b
Create Date: 2026-04-28 13:26:39.240082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f80ffeed5b87'
down_revision: Union[str, Sequence[str], None] = 'ff93234e580b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weatherhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('point_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('shortwave_radiation', sa.Float(), nullable=False),
    sa.Column('diffuse_radiation', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('windspeed_10m', sa.Float(), nullable=False),
    sa.Column('cloudcover_high', sa.Float(), nullable=False),
    sa.Column('cloudcover_medium', sa.Float(), nullable=False),
    sa.Column('cloudcover_low', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time', 'point_id')
    )
    op.create_index(op.f('ix_weatherhistory_point_id'), 'weatherhistory', ['point_id'], unique=False)
    op.create_table('weatherforecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('temperature_2m', sa.Float(), nullable=True),
    sa.Column('shortwave_radiation', sa.Float(), nullable=True),
    sa.Column('diffuse_radiation', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('windspeed_10m', sa.Float(), nullable=True),
    sa.Column('cloudcover_high', sa.Float(), nullable=True),
    sa.Column('cloudcover_medium', sa.Float(), nullable=True),
    sa.Column('cloudcover_low', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['installation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'target_time', 'reference_time')
    )
    op.add_column('installation', sa.Column('panel_angle', sa.Float(), nullable=True))
    op.add_column('installation', sa.Column('panel_orientation', sa.Float(), nullable=True))
    op.add_column('installation', sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('installation', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installation', 'model')
    op.drop_column('installation', 'manufacturer')
    op.drop_column('installation', 'panel_orientation')
    op.drop_column('installation', 'panel_angle')
    op.drop_table('weatherforecast')
    op.drop_index(op.f('ix_weatherhistory_point_id'), table_name='weatherhistory')
    op.drop_table('weatherhistory')
    # ### end Alembic commands ###
