"""Add missing unique constraints

Revision ID: ff93234e580b
Revises: f09934c53fbc
Create Date: 2026-04-23 21:47:00.326862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "ff93234e580b"
down_revision: Union[str, Sequence[str], None] = "f09934c53fbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "smartplugmeasure", ["time", "smartplug_id"])
    op.create_unique_constraint(
        None, "userinstallationlink", ["user_id", "installation_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userinstallationlink", type_="unique")
    op.drop_constraint(None, "smartplugmeasure", type_="unique")
    # ### end Alembic commands ###
